#version: '3.8'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    environment:
      - node.name=elasticsearch
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:${ES_PORT}
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    environment:
      - node.name=kibana
      # CLUSTER_NAME comes from .env file
      - cluster.name=${CLUSTER_NAME}
      # ELASTICSEARCH_HOSTS is the hostname of the elasticsearch service comes from container name
      - ELASTICSEARCH_HOSTS=http://elasticsearch:${ES_PORT}
    ports:
      - ${KIBANA_PORT}:${KIBANA_PORT}
    networks:
      - elastic
    depends_on:
      - elasticsearch
  seq:
    image: datalust/seq:latest
    ports:
       - '5300:80'
       - '5341:5341'
    volumes:
       - seq-data:/data
    environment:
      ACCEPT_EULA: Y
  
networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: c:/elasticsearch/data
  
  seq-data:
    